### PR TITLE
include definitions for TND and UND

### LINKED ISSUE #20: define the conditions for the *TND* and *UND*
we agreed to use the *TND* and *UND* acronyms when referring to the trusted/untrusted / trustworthy/un and inside/outside domains. _But_ we should probably define what is expected of those domains so that fleets and OEM can evaluate applicability of the requirements.

### PR DESCRIPTION
**Pull request by BenGardiner**
resolves #20 , thanks to Julia Coniglio!

### CODE REVIEW

**Comment by BenGardiner** [comment]
NB: @kentindell when this merges then the UIDs you need to reference should be stable

**Comment by BenGardiner** [comment]
👋 @jmaag15

**Comment by jmaag15** [comment]
Reviewed and merged

**Comment by BenGardiner** [comment]
Thanks @jmaag15 !

**Pull request merged**
