### PR TITLE
adding public references

### PR DESCRIPTION
**Pull request by BenGardiner**

### CODE REVIEW

**Review by rittmuller-volpe — APPROVED** [review]
Looks good, but we should also consider what format references use and if those references should be automatically "clickable" vs. static text. (This really depends on the primary use case).

**Comment by BenGardiner** [comment]
ok @jmaag15 this matches WG consensus from 20220824 meeting now

**Comment by BenGardiner** [comment]
@jmaag15 ping3

**Comment by jmaag15** [comment]
Updates as discussed 20220824, merging

**Pull request merged**
